version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '${GRAPHQL_HOST_PORT:-8000}:8000'
      - '${GRAPHQL_WS_HOST_PORT:-8001}:8001'
      - '${JSONRPC_HOST_PORT:-8020}:8020'
      - '${INDEX_NODE_SERVER_HOST_PORT:-8030}:8030'
      - '${METRICS_SERVER_HOST_PORT:-8040}:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:${RPC_URL:-http://janus_mainnet:23890}'
      GRAPH_LOG: ${LOG_LEVEL:-info}
      GRAPH_QUERY_CACHE_MAX_MEM: ${GRAPH_QUERY_CACHE_MAX_MEM:-1000}
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: ${GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE:-1000}
      GRAPH_ETHEREUM_MAX_EVENT_ONLY_RANGE: ${GRAPH_ETHEREUM_MAX_EVENT_ONLY_RANGE:-500}
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE:-100}
  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - '${IPFS_HOST_PORT:-5001}:5001'
    volumes:
      - ./data/ipfs:/data/ipfs:Z
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_HOST_PORT:-5432}:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z
